### ISSUE TITLE
Line spacing is broken

### ISSUE THREAD

**Issue by havrikov** [chrmatt/algpseudocodex#2] opened 2021-06-07 10:53 UTC
Since the latest update to the TexLive and MikTeX distributions (as of `2021-06-06`) the spacing between the lines in `algpseudocodex` is off, and as a result, the indent lines are also misplaced.  
Consider the following snippet:

```tex
\documentclass[10pt,a4paper]{book}

\usepackage{algorithm}
\usepackage{algpseudocodex}

\begin{document}

\begin{algorithm}
  \caption{Example Algorithm}
  \label{alg:example}
  \begin{algorithmic}[1]
    \Function{foo}{x,y}
    \While{\(x \ne y\)}
    \State \(x\gets x+1\) \Comment{Hello there}
    \EndWhile
    \State \Return \(x\)
    \EndFunction
  \end{algorithmic}
\end{algorithm}

\end{document}
```

Since the update, it renders as follows:

![Screenshot 2021-06-07 124125](https://user-images.githubusercontent.com/29175267/121004772-5b3e6a80-c78f-11eb-8124-d7cff1eb41c9.png)

**Comment by chrmatt** [comment] 2021-06-07 21:28
This is caused by a new behavior in the `varwidth` package that `algpseudocodex` is using internally, see https://tex.stackexchange.com/q/600349/123920.

**Comment by chrmatt** [comment] 2021-06-08 14:44
This answer on StackExchange describes a workaround that fixes the problem: https://tex.stackexchange.com/a/600420/123920
I hope that `varwidth` will get fixed soon and I don't plan to implement a workaround in `algpseudocodex` for now.

**Comment by havrikov** [comment] 2021-06-08 14:56
Understood.  
Thank you for clarifying.  

FWIW, this is what it looks like with the workaround applied:
![Screenshot 2021-06-08 173558](https://user-images.githubusercontent.com/29175267/121215138-09c1d880-c880-11eb-821e-7d4c2696b3c6.png)


As you can see, the comment is still slightly offset with regards to its line.  
Nevertheless, feel free to close this issue.

**Comment by chrmatt** [comment] 2021-06-08 15:41
Thanks for pointing out the offset comments! The problem seems to disappear if you use `rightComments=false`. I'll leave this open and hope it will be fixed soon with a proper fix of `varwidth`.

If you need a properly formatted document now and you don't use `\BeginBox` and `\EndBox`, you can download a copy of  `algpseudocodex.sty` and replace `varwidth` with `minipage` everywhere in there. This fixes it for me (but makes all boxes maximal width).

**Comment by chrmatt** [comment] 2021-06-26 23:17
Issue appears to be fixed in newest version of TeX Live (including the offset comments).

**Closed as completed** 2021-06-26 23:17 UTC
